// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uixsodhskooqajszoxbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpeHNvZGhza29vcWFqc3pveGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMDQ1NDcsImV4cCI6MjA4OTY4MDU0N30.AdQ2Do6MxAFlkeReRgG6q_-DoCS6PoOjmV5u3HrClQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});